spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5555/api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true

server:
  port: 8070
  error:
    include-stacktrace: never