services:
  db:
    image: postgres
    container_name: api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
    volumes:
      - postgres_data_api:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    networks:
      - app-network

volumes:
  postgres_data_api:

networks:
  app-network: